export const activityTable = {
  table: "table",
  tableHeaders: "table thead th",
  tableRows: '[data-cy^="linha-atividade-"]',
  actionsButton: 'button[data-cy$="-btn-menu"]',
  editButton: 'button[data-cy$="-btn-editar"]',
  deleteButton: 'button[data-cy$="-btn-excluir"]',
  duplicateButton: 'button[data-cy$="-btn-duplicar"]',
  statusSelect: 'select[data-cy^="status-dropdown-"]',
  rejectionReasonModal: '[data-cy="modal-rejeicao"]',
  rejectionReasonInput: 'textarea[data-cy="modal-rejeicao-motivo"]',
  rejectionReasonRequiredAlert: 'p[data-cy="modal-rejeicao-erro"]',
  confirmRejectButton: 'button[data-cy="modal-rejeicao-btn-confirmar"]',
  cancelRejectButton: 'button[data-cy="modal-rejeicao-btn-cancelar"]',
};
